package com.example.orderservice.domain.enums;

public enum EOrderEventType {
  INVENTORY_NOT_RESERVED,
  INVENTORY_RESERVED,
  TRANSACTION_COMPLETED,
  TRANSACTION_FAILED,
  ORDER_SHIPPED,
  ORDER_COMPLETED,
  ORDER_CANCELLED,
  ORDER_ACCEPTED,
  ORDER_REQUESTED
}
