apiVersion: v1
kind: Service
metadata:
  name: inventory-service-db-service
  labels:
    app: inventory-service-db-service
    tier: database
  namespace: edms
spec:
  ports:
    - port: 5432
      targetPort: 5432
  selector:
    app: inventory-service-db
    tier: database

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventory-service-db
  labels:
    app: inventory-service-db
    tier: database
  namespace: edms
spec:
  selector:
    matchLabels:
      app: inventory-service-db
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: inventory-service-db
        tier: database
    spec:
      containers:
        - name: inventory-service-db
          image: postgres:12
          imagePullPolicy: "IfNotPresent"
          env:
            - name: POSTGRES_DB
              value: inventorydb
            - name: POSTGRES_USER
              value: inventory
            - name: POSTGRES_PASSWORD
              value: password
          ports:
            - containerPort: 5432

---
apiVersion: v1
kind: Service
metadata:
  name: inventory-service-service
  namespace: edms
spec:
  ports:
    - protocol: "TCP"
      port: 8080
      targetPort: 8080
  selector:
    app: inventory-service
  type: NodePort

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventory-service
  namespace: edms
spec:
  replicas: 1
  selector:
    matchLabels:
      app: inventory-service
  template:
    metadata:
      labels:
        app: inventory-service
    spec:
      containers:
        - image: tynas/inventory-service
          name: inventory-service
          ports:
            - containerPort: 8080
          env:
            - name: DB_URI
              value: host=inventory-service-db-service user=inventory password=password dbname=inventorydb port=5432
            - name: KAFKA_BOOTSTRAP_ADDRESS
              value: "kafka-service:9092"
            - name: PORT
              value: "8080"
