# order service
apiVersion: v1
kind: Service
metadata:
  name: postgresql
  labels:
    app: postgresql
    tier: database
  namespace: edms
spec:
  ports:
    - port: 5432
      targetPort: 5432
  selector:
    app: postgresql
    tier: database

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgresql
  labels:
    app: postgresql
    tier: database
  namespace: edms
spec:
  selector:
    matchLabels:
      app: postgresql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: postgresql
        tier: database
    spec:
      containers:
        - name: postgresql
          image: postgres:12
          imagePullPolicy: "IfNotPresent"
          env:
            - name: POSTGRES_DB
              value: orderdb
            - name: POSTGRES_USER
              value: order
            - name: POSTGRES_PASSWORD
              value: password
          ports:
            - containerPort: 5432

---
apiVersion: v1
kind: Service
metadata:
  name: order-service-service
  namespace: edms
spec:
  ports:
    - protocol: "TCP"
      port: 8080
      targetPort: 8080
  selector:
    app: order-service
  type: NodePort

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service
  namespace: edms
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-service
  template:
    metadata:
      labels:
        app: order-service
    spec:
      containers:
        - image: tynas/order-service
          name: order-service
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_DATASOURCE_PASSWORD
              value: password
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://postgresql:5432/orderdb?createDatabaseIfNotExist=true
            - name: SPRING_DATASOURCE_USERNAME
              value: order
            - name: SPRING_JPA_HIBERNATE_DDL_AUTO
              value: update
            - name: EDMS_KAFKA_BOOTSTRAP_ADDRESS
              value: kafka-service:9092
            - name: EDMS_USER_SERVICE_URL
              value: http://user-service-service:8080
