# shipping service
apiVersion: apps/v1
kind: Deployment
metadata:
  name: shipping-service
  namespace: edms
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shipping-service
  template:
    metadata:
      labels:
        app: shipping-service
    spec:
      containers:
        - image: tynas/shipping-service
          name: shipping-service
          env:
            - name: KAFKA_BOOTSTRAP_ADDRESS
              value: "kafka-service:9092"
