apiVersion: v1
kind: Service
metadata:
  name: user-service-db-service
  labels:
    app: user-service-db-service
    tier: database
  namespace: edms
spec:
  ports:
    - port: 5434
      targetPort: 3306
  selector:
    app: user-service-db
    tier: database

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service-db
  labels:
    app: user-service-db
    tier: database
  namespace: edms
spec:
  selector:
    matchLabels:
      app: user-service-db
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: user-service-db
        tier: database
    spec:
      containers:
        - name: user-service-db
          image: mysql:5.7
          imagePullPolicy: "IfNotPresent"
          env:
            - name: MYSQL_DATABASE
              value: userdb
            - name: MYSQL_USER
              value: user
            - name: MYSQL_PASSWORD
              value: password
            - name: MYSQL_ROOT_PASSWORD
              value: password

          ports:
            - containerPort: 3306

---
apiVersion: v1
kind: Service
metadata:
  name: user-service-service
  namespace: edms
spec:
  ports:
    - protocol: "TCP"
      port: 8080
      targetPort: 8080
  selector:
    app: user-service
  type: NodePort

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
  namespace: edms
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
      containers:
        - image: tynas/user-service
          name: user-service
          ports:
            - containerPort: 8080
          env:
            - name: DB_URI
              value: user:password@tcp(user-service-db-service:5434)/userdb?parseTime=true
            - name: PORT
              value: "8080"
