version: "3.7"

services:
  # Payment service (Python and Flask REST API)
  payment_service:
    build:
      context: ./
    environment:
      - PYTHONUNBUFFERED=1
    ports:
      - 8081:5000
    volumes:
      - .:/app

networks:
  default:
    external:
      name: edms_network
