version: "3.7"

services:
  # Payment service (Python)
  payment_service:
    build: .
    container_name: edms-payment-service
    environment:
      - PYTHONUNBUFFERED=1
      - KAFKA_BROKER_ADDRESS=kafka:9092
    volumes:
      - .:/app

networks:
  default:
    name: edms_network
    external: true
