version: "3.8"

services:
  # User Service (Go and Gin REST API)
  user-service:
    build:
      context: .
      dockerfile: ./Dockerfile.development
    env_file:
      - .env
    ports:
      - 8082:3000
    depends_on:
      user-service-db:
        condition: service_healthy
    volumes:
      - .:/usr/src/app
    command: air src/main.go -b 0.0.0.0

  # User service database (MySQL)
  user-service-db:
    image: mysql:5.7
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    ports:
      - "5434:3306"
    volumes:
      - user-service-postgres-db-volume:/var/lib/mysql
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u $$MYSQL_USER --password=$$MYSQL_PASSWORD
      start_period: 5s
      interval: 5s
      timeout: 5s
      retries: 55

volumes:
  user-service-postgres-db-volume:

networks:
  default:
    external:
      name: edms_network
