version: "3.8"

services:
  # User Service (Go and Gin REST API)
  user-service:
    build: .
    env_file:
      - .env
    ports:
      - 8082:3000
    depends_on:
      - user-service-db
    volumes:
      - .:/usr/src/app
    command: air src/main.go -b 0.0.0.0

  # User service database (MySQL)
  user-service-db:
    image: mysql:5.7
    restart: always
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    ports:
      - "5434:3306"
    volumes:
      - user-service-postgres-db-volume:/var/lib/mysql

volumes:
  user-service-postgres-db-volume:
