version: "3.8"

services:
  shipping-service:
    build:
      context: .
    command: >
      sh -c "cargo test &&
             cargo run"

    volumes:
      - .:/usr/src/app
      - registry:/root/.cargo/registry # cache new crates when they are installed

volumes:
  registry:
    driver: local
