version: "3.0"

services:
  shipping-service:
    container_name: edms-shipping-service
    build:
      context: .
      dockerfile: ./Dockerfile.local
    environment:
      - KAFKA_BOOTSTRAP_ADDRESS=kafka:9092

networks:
  default:
    name: edms_network
    external: true
