version: "3.0"

services:
  shipping-service:
    build: .
    environment:
      - KAFKA_BOOTSTRAP_ADDRESS=kafka:9092
    volumes:
      - .:/usr/app

networks:
  default:
    external:
      name: edms_network
