version: "3.0"

services:
  shipping-service:
    build:
      context: .
    command: >
      sh -c "cargo test &&
            cargo run"
    volumes:
      - .:/usr/src/app
      - registry:/root/.cargo/registry

volumes:
  registry:
    driver: local

networks:
  default:
    external:
      name: edms_network
